spring:
  profiles: local
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    password: test123
    username: postgres
    hikaki:
      maximum-pool-size: 20
      schema: measurements
    url: jdbc:postgresql://localhost:30000/measurements
server:
  port: 8080
de:
  heinze:
    measurements:
      dht22:
        polling-interval: 60
      humidity-limit: 40.0
      temperature-limit: 23.0
logging:
  config: classpath:logback-local.xml