spring:
  profiles: rasp
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    password: test123
    username: postgres
    hikaki:
      maximum-pool-size: 20
      schema: measurements
    url: jdbc:postgresql://localhost:5432/measurements
server:
  port: 8080
de:
  heinze:
    measurements:
      dht22:
        polling-interval: 60
logging:
  config: classpath:logback-rasp.xml